# .pre-commit-config.yaml  (top level)

default_language_version:
  python: python3.10 # or python3 if you don’t care about minor

repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        # This override is now optional, feel free to delete it:
        # language_version: python3.10

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.7
    hooks: [id: ruff]

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks: [id: isort]

  # .pre-commit-config.yaml
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.2 # ← use the tip-of-tree instead of a tag
    hooks:
      - id: toml-sort
        args: ["--check"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks: [id: prettier]

  - repo: local
    hooks:
      - id: pytest
        name: pytest (collect only)
        entry: pytest tests --collect-only
        pass_filenames: false
        language: system
        always_run: true
