name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.10'}
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - run: pip install .            # editable install of your package
      - run: ruff .                   # fast lint (≈1 s)
      - run: pytest -q --cov=aged_care_pipeline --cov-report=xml
      - uses: actions/upload-artifact@v4
        with: {name: coverage, path: coverage.xml}